name: Sync issues to jira
on:
  issues:
    types: [labeled]
jobs:
  issue-sync:
    permissions:
      issues: write # should be set
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0' # The Go version should be grater than 1.19.0
      - name: Sync to Jira
        uses: atsushii/github-issue-to-jira@v1
        with:
          github-owner: github-owner
          github-repo: repository-name
          github-token: ${{ secrets.GITHUB_TOKEN }} # read/write authorized token
          jira-hostname: hostname # Your Sync dest Jira hostname
          jira-auth-token: ${{ secrets.JIRA_AUTH_TOKEN }} # Your Jira auth token
          jira-auth-email: ${{ secrets.JIRA_AUTH_EMAIL }} # email same as jira project creator
          jira-project-key: project-key # Your Sync dest Jira project name
          jira-issue-type: custom-jira-issue-type