name: Jira Sync
on:
  issues:
    types: [opened, labeled, unlabeled]
  issue_comment:
    types: [created]
jobs:
  sync:
    name: Sync Items
    runs-on: ubuntu-latest
    steps:
      - name: Sync Github Issues to Jira
        uses: mheap/github-action-issue-to-jira@v1
        env:
          GITHUB_TOKEN: ${{ secrets.JIRA_TOKEN}}
        with:
          jiraHost: ${{ secrets.JIRA_HOST }}
          jiraUsername: ${{ secrets.JIRA_AUTH_EMAIL }}
          jiraPassword: ${{ secrets.JIRA_AUTH_TOKEN }} # See https://id.atlassian.com/manage/api-tokens
          project: kuberada-blog
          assignee: colossus06